---
title: "Untitled"
author: "Dustin Kincaid"
date: "3/29/2021"
output: html_document
---



```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Plot NO3 & SRP yields against water yield
som_hf %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2), names_to = "var", values_to = "value") %>% 
  ggplot(aes(x = q_mm, y = value)) +
    facet_wrap(~var, ncol = 1, scales = "free_y") +
    geom_point(aes(color = as.factor(cluster)), size = 2, stroke = 0.75, alpha = 0.8) +
    geom_smooth(method=lm, se=TRUE) +
    scale_color_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab(expression(Event~NO[3]^-{}~or~SRP~yield~(kg~N~or~P~km^{-2}))) +
    xlab("Event water yield (mm)") +
    # scale_y_continuous(limits = c(0, 1300), breaks=seq(0, 1200, 300)) +
    # facet_wrap(~site, labeller = labeller(var = labels, site = labels2)) +
    # theme1
    theme_classic() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_blank())
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Plot NO3:SRP yield ratios against water yield
som_hf %>% 
  ggplot(aes(x = q_mm, y = log(event_NO3_SRP), color = as.factor(cluster))) +
    geom_point(size = 2, stroke = 0.75, alpha = 0.8) +
    scale_color_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    # geom_hline(yintercept = 16, linetype = "dashed", size = 0.75, color = "gray40") +
    # ylab(expression(paste(Ratio~of~"NO"["3"]^" -"~" : "~SRP~event~yield))) + 
    ylab(expression(atop(log~Molar~ratio~of~NO[3]^-{}~":"~SRP~yield, "for"~each~event))) +
    xlab("Event water yield (mm)") +
    # scale_y_continuous(limits = c(0, 1300), breaks=seq(0, 1200, 300)) +
    # facet_wrap(~site, labeller = labeller(var = labels, site = labels2)) +
    theme1

ggsave(here("Plots", "SOM_hf_ratiosBYWaterYield.pdf"), device = "pdf",  width = 4, height = 4, units = "in", dpi = 150)
```
<br><br>

```{r, include = FALSE}
# Text for Clockwise, Counterclockwise, Diluting, Flushing on the plots
text_cw <- textGrob("Clockwise", gp = gpar(fontsize = 10))
text_ccw <- textGrob("Counterclockwise", gp = gpar(fontsize = 10))
text_dil <- textGrob("Diluting", gp = gpar(fontsize = 10), rot = 90)
text_flu <- textGrob("Flushing", gp = gpar(fontsize = 10), rot = 270)

# Nitrate
pl_hifi_no3 <- 
  datWithCluster %>% 
  left_join(hyst %>% filter(site == "Hungerford"), by = c("site", "event_start")) %>%
  ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = FI_NO3, y = HI_NO3_mean, color = as.factor(cluster)), size = 2, alpha = 0.8) +
  scale_color_manual(name = "Cluster",
                     values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
  ylim(-1, 1) + xlim(-1, 1) +
  ylab("Storm hysteresis index") + xlab("Storm flushing index") +
  theme3 +
  ggtitle("Nitrate") + 
  theme(plot.title = element_text(hjust = 0, size = 12),
        legend.position = c(0.8, 0.85),
        legend.box = "horizontal") +
  annotation_custom(text_dil, xmin=-1.45, xmax=-1.45, ymin=0, ymax=0) +
  annotation_custom(text_flu, xmin=1.2, xmax=1.2, ymin=0, ymax=0) +
  annotation_custom(text_cw, xmin=0, xmax=0, ymin=1.2, ymax=1.2) +
  annotation_custom(text_ccw, xmin=0, xmax=0, ymin=-1.4, ymax=-1.4) +
  coord_cartesian(clip = "off")

# SRP
pl_hifi_srp <- 
  datWithCluster %>% 
  left_join(hyst %>% filter(site == "Hungerford"), by = c("site", "event_start")) %>%
  ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = FI_SRP, y = HI_SRP_mean, color = as.factor(cluster)), size = 2, alpha = 0.8) +
  scale_color_manual(name = "Cluster",
                     values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
  ylim(-1, 1) + xlim(-1, 1) +
  ylab("Storm hysteresis index") + xlab("Storm flushing index") +
  theme3 +
  ggtitle("SRP") + 
  theme(plot.title = element_text(hjust = 0, size = 12),
        legend.position = "none") +
  annotation_custom(text_dil, xmin=-1.45, xmax=-1.45, ymin=0, ymax=0) +
  annotation_custom(text_flu, xmin=1.2, xmax=1.2, ymin=0, ymax=0) +
  annotation_custom(text_cw, xmin=0, xmax=0, ymin=1.2, ymax=1.2) +
  annotation_custom(text_ccw, xmin=0, xmax=0, ymin=-1.4, ymax=-1.4) +
  coord_cartesian(clip = "off")

# Combine the 2 plots into one
pl_HI_v_FI_alt <- plot_grid(pl_hifi_no3, pl_hifi_srp, ncol = 2, align = "hv",
                            labels = "auto", hjust = -0.4, vjust = 2.5, scale = 1)
# Create common x and y axis titles
y.grob <- textGrob("Storm hysteresis index",
                   gp = gpar(fontsize = 13), rot = 90)
x.grob <- textGrob("Storm flushing index",
                   gp = gpar(fontsize = 13))
# Add axis title to plot
# test_alt <- grid.arrange(arrangeGrob(pl_HI_v_FI_alt, left = y.grob, bottom = x.grob))
# ggsave("Plots/HIFI_hf.png", test_alt, width = 6, height = 3.5, units = "in", dpi = 300)     
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Add axis title to plot
# grid.arrange(arrangeGrob(pl_HI_v_FI_alt, left = y.grob, bottom = x.grob))
test_alt <- grid.arrange(arrangeGrob(pl_HI_v_FI_alt, left = y.grob, bottom = x.grob))
ggsave(here("Plots", "HIFI_hf.pdf"), plot = test_alt, device = "pdf", width = 6, height = 3.5, units = "in", dpi = 300)     
```
<br><br>

#### How do our results differ if we choose the 2nd best SOM run?
```{r, include = TRUE, echo = FALSE, message = FALSE}
# Select the top one
best_summ_2ndBest <-
  best_summ_top %>% 
  slice(2:2)

noquote("The 2nd best run was:")
best_summ_2ndBest %>% 
  mutate_at(vars(c(npF, QE)),
            .funs = ~round(., 3)) %>%     
  gt()

# Choose lattice dimensions you want to examine based on npf/QE plot above
  n_rows_2 = best_summ_2ndBest$rows
  n_cols_2 = best_summ_2ndBest$cols
  n_clust_2 = best_summ_2ndBest$Clusters

# Which Run is best?
  best_run_2 = best_summ_2ndBest$Run

# CREATE DF WITH EVENT IDs & CLUSTER #'s ----  
datWithCluster2 <- clustAssignmDF %>% 
  # Parse columns into correct type
  type_convert() %>% 
  filter(Run == best_run_2) %>% 
  # Pivot to longer format
  pivot_longer(cols = obs1:ncol(.), names_to = "obs", values_to = "cluster") %>% 
  select(cluster) %>% 
  # Bind cluster ID to myData
  bind_cols(myData) %>% 
  # Join to original data to get event IDs
  left_join(hford) %>% 
  mutate(event_start = ymd_hms(event_start, tz = "Etc/GMT+4")) %>% 
  # Drop all the independent variables you didn't use in the SOM (copy from myData above); 
  # but KEEP the INFO vars
  select(-one_of(drop.vars)) %>% 
  # Arrange columns
  select(site:ncol(.), everything())
  
  # Write to CSV
  # datWithCluster %>% 
  #   mutate(event_start = as.character(event_start)) %>% 
  #   write_csv(here(paste0(newFolder, "/", "SOMresults", "_", myDataSet, "_", Sys.Date(), "_", nclusters, "cl", "_", n_rows, "x", n_cols, ".csv")))
```
<br><br>

To examine this run in greater detail (e.g., component planes), see the 'X_SOMplots_site_ ... .pdf'  
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE, fig.asp = 1.4}
# BOXPLOTS OF INDEPENDENT VARIABLES BY CLUSTER ----
  # # of plots (use this to decide how many PDF pages you want to plot all the plots on)
  df2 <- datWithCluster2 %>% 
    pivot_longer(cols = DOY:ncol(.), names_to = "var", values_to = "value")
  # length(unique(df$var))

  datWithCluster2 %>% 
    pivot_longer(cols = DOY:ncol(.), names_to = "var", values_to = "value") %>% 
    ggplot(aes(x = cluster, y = value, group = cluster)) +
    facet_wrap(~var, scales = "free_y", ncol = 4) +
    geom_boxplot(fill = "white") +
    geom_point(position=position_jitter(width=0.2), shape=1, size=1, color="gray50", alpha=0.6) +
    ylab("Value") + xlab("Cluster") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          strip.text = element_text(size = 7),
          panel.spacing.x = unit(0.3, "inches"),
          panel.spacing.y = unit(0.45, "inches"))
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE, fig.asp = 1}
# Look at z-scores by cluster
datWithCluster2 %>% 
  # Rename clusters
  mutate(cluster = paste("Cluster", cluster, sep = " ")) %>% 
  # Calculate z-scores for each independent variable
  mutate_at(vars(c(DOY:ncol(.))),
          .funs = list(~ (. - mean(., na.rm = T)) / sd(., na.rm = T))) %>%
  pivot_longer(cols = DOY:ncol(.), names_to = "var", values_to = "value") %>% 
  group_by(cluster, var) %>% 
  summarize(median = median(value, na.rm = T)) %>% 
  # Order the vars n var
  mutate(var = factor(var, levels = c("turb_event_max", "multipeak", "q_mm", "rain_event_total_mm", "rain_event_hrs", "rain_int_mmPERmin_mean", "SRP_1d", "NO3_1d",
                                      "q_4d", "time_sinceLastEvent", "API_4d", "Redox_pre_wet_15cm", "DO_pre_wet_15cm", "VWC_pre_wet_15cm", "SoilTemp_pre_wet_15cm", 
                                      "solarRad_4d", "PET_mmHR", "diff_airT_soilT", "DOY"))) %>% 
  ggplot(aes(x = var, y = median)) +
    # Must use scales = "free" when using the reordering functions
    facet_wrap(~cluster, ncol = 2) +
    geom_bar(stat = "identity") +
    # scale_x_reordered() +
    ylab("Median z-scores") +
    coord_flip() +
    theme_bw() +
    theme(panel.grid = element_blank(),
          axis.title.y = element_blank()) +
  ggtitle("Characteristics of each cluster - median z-scores")

# ggsave(here("Plots", "SOM_hf_zScoresByCluster.pdf"), device = "pdf", width = 6, height = 6, units = "in", dpi = 150)

# Plotting mean z-scores + SE
datWithCluster2 %>% 
  # Rename clusters
  mutate(cluster = paste("Cluster", cluster, sep = " ")) %>% 
  # Calculate z-scores for each independent variable
  mutate_at(vars(c(DOY:ncol(.))),
          .funs = list(~ (. - mean(., na.rm = T)) / sd(., na.rm = T))) %>%
  pivot_longer(cols = DOY:ncol(.), names_to = "var", values_to = "value") %>% 
  group_by(cluster, var) %>% 
  summarize(mean = mean(value),
            SE = sd(value)/sqrt(length(!is.na(value)))) %>% 
  # Order the vars n var
  mutate(var = factor(var, levels = c("turb_event_max", "multipeak", "q_mm", "rain_event_total_mm", "rain_event_hrs", "rain_int_mmPERmin_mean", "SRP_1d", "NO3_1d",
                                      "q_4d", "time_sinceLastEvent", "API_4d", "Redox_pre_wet_15cm", "DO_pre_wet_15cm", "VWC_pre_wet_15cm", "SoilTemp_pre_wet_15cm", 
                                      "solarRad_4d", "PET_mmHR", "diff_airT_soilT", "DOY"))) %>%   
  ggplot(aes(x = var, y = mean)) +
    # Must use scales = "free" when using the reordering functions
    facet_wrap(~cluster, ncol = 2) +
    geom_bar(stat = "identity", position = position_dodge()) +
    geom_errorbar(aes(ymin = mean - SE, ymax = mean + SE), width = 0.2, position = position_dodge(0.9)) +
    # scale_x_reordered() +
    ylab("Median z-scores") +
    coord_flip() +
    theme_bw() +
    theme(panel.grid = element_blank(),
          axis.title.y = element_blank()) +
  ggtitle("Characteristics of each cluster - mean z-scores +/- SEM")
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
datWithCluster2 %>% 
  group_by(cluster, season) %>% 
  tally() %>% 
  # Order the seasons
  mutate(season = factor(season, levels = c("spring", "summer", "fall"), labels = c("Spring", "Summer", "Fall"))) %>%
  mutate(cluster = factor(cluster)) %>% 
  ggplot(aes(x = season, y = n, fill = cluster)) +
    geom_bar(position = "stack", stat = "identity") +
    scale_fill_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab("No. of events") +
    xlab("Season") +
    theme1

# ggsave(here("Plots", "SOM_hf_clustersBySeason.pdf"), device = "pdf", width = 4, height = 4, units = "in", dpi = 150)
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE, out.width = "80%"}
# Plot timeline of event yields & ratios colored by cluster number
datWithCluster2 %>% 
  # Only 2 events in 2017, so cutting out 2017
  filter(year(event_start) != 2017) %>% 
   # Add leading zero to single digit months and days
  mutate(year = year(event_start),
         month = str_pad(month(event_start), 2, pad = 0),
         day = str_pad(day(event_start), 2, pad = 0),
         month_day = paste(month, "/", day, sep = "")) %>%
  # There is one day where there are two events, add a rep for month_day and make month_day_rep ID
  group_by(year, month_day) %>% 
  mutate(rep = row_number()) %>% 
  mutate(month_day_rep = paste(month_day, rep, sep = "-")) %>% 
  # Calculate log of NO3:SRP yield ration
  mutate(log_event_NO3_SRP = log(event_NO3_SRP)) %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2, log_event_NO3_SRP), names_to = "var", values_to = "value") %>% 
  mutate(var = factor(var, levels = c("NO3_kg_km2", "SRP_kg_km2", "log_event_NO3_SRP"))) %>% 
  
  ggplot(aes(x = month_day_rep, y = value, fill = as.factor(cluster))) +
    # facet_wrap(var ~ year, scales = "free", ncol = 2) +
    facet_grid(var ~ year, scales = "free") +
    geom_bar(stat = "identity") +
    scale_fill_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab(expression(Yield~(kg~N~or~P~km^{-2})~or~yield~ratio)) +
    xlab("Date (month/day - #)") +
    theme_bw() +
    theme(panel.grid = element_blank(),
          strip.text.x = element_text(size = 8),
          axis.text.x = element_text(angle = 90))

# ggsave(here("Plots", "SOM_hf_eventsByCluster.pdf"), device = "pdf", width = 10, height = 6, units = "in", dpi = 150)
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Plot total yield attributed to each cluster #

# Calculate annual yields
annYields2 <-
  datWithCluster2 %>% 
  # Calculate the cummulative sum of yields for each solute, year, and cluster #
  mutate(year = year(event_start)) %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2), names_to = "var", values_to = "value") %>% 
  group_by(year, var) %>% 
  summarize(ann_yield = sum(value, na.rm = TRUE))

# Stacked bar graph (year on x-axis; stacks = yields by cluster)
# Total
datWithCluster2 %>% 
  # Calculate the cummulative sum of yields for each solute, year, and cluster #
  mutate(year = year(event_start)) %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2), names_to = "var", values_to = "value") %>% 
  group_by(year, cluster, var) %>% 
  summarize(tot_yield = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # Exclude 2017 events  
  filter(year != 2017) %>% 
  ggplot(aes(x = factor(year), y = tot_yield, fill = factor(cluster))) +
    facet_wrap(~var, ncol = 2, scales = "free_y", labeller = labeller(var = labels_var)) +
    geom_bar(position = "stack", stat = "identity") +
    scale_fill_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab(expression(Annual~event~yield~(kg~N~or~P~km^{-2}))) +
    xlab("Year") +
    # theme1 +
    theme_classic() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_blank())

# Proportional
datWithCluster2 %>% 
  # Calculate the cummulative sum of yields for each solute, year, and cluster #
  mutate(year = year(event_start)) %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2), names_to = "var", values_to = "value") %>% 
  group_by(year, cluster, var) %>% 
  summarize(tot_yield = sum(value, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # Calculate proportion of total annual yield
  full_join(annYields2) %>% 
  mutate(prop_yield = tot_yield/ann_yield) %>% 
  # Exclude 2017 events
  filter(year != 2017) %>% 
  ggplot(aes(x = factor(year), y = prop_yield, fill = factor(cluster))) +
    facet_wrap(~var, ncol = 2, scales = "free_y", labeller = labeller(var = labels_var)) +
    geom_bar(position = "stack", stat = "identity") +
    scale_fill_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab(expression(Proportion~of~annual~event~yield~(kg~N~or~P~km^{-2}))) +
    xlab("Year") +
    # theme1 +
    theme_classic() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_blank())
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Plot NO3 & SRP yields against water yield
datWithCluster2 %>% 
  pivot_longer(cols = c(NO3_kg_km2, SRP_kg_km2), names_to = "var", values_to = "value") %>% 
  ggplot(aes(x = q_mm, y = value)) +
    facet_wrap(~var, ncol = 1, scales = "free_y", labeller = labeller(var = labels_var)) +
    geom_point(aes(color = as.factor(cluster)), size = 2, stroke = 0.75, alpha = 0.8) +
    geom_smooth(method=lm, se=TRUE) +
    scale_color_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    ylab(expression(Event~NO[3]^-{}~or~SRP~yield~(kg~N~or~P~km^{-2}))) +
    xlab("Event water yield (mm)") +
    # scale_y_continuous(limits = c(0, 1300), breaks=seq(0, 1200, 300)) +
    # facet_wrap(~site, labeller = labeller(var = labels, site = labels2)) +
    # theme1
    theme_classic() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_blank())
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Plot NO3:SRP yield ratios against water yield
datWithCluster2 %>% 
  ggplot(aes(x = q_mm, y = log(event_NO3_SRP), color = as.factor(cluster))) +
    geom_point(size = 2, stroke = 0.75, alpha = 0.8) +
    scale_color_manual(name = "Cluster",
                      values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
    # geom_hline(yintercept = 16, linetype = "dashed", size = 0.75, color = "gray40") +
    # ylab(expression(paste(Ratio~of~"NO"["3"]^" -"~" : "~SRP~event~yield))) + 
    ylab(expression(atop(log~Molar~ratio~of~NO[3]^-{}~":"~SRP~yield, "for"~each~event))) +
    xlab("Event water yield (mm)") +
    # scale_y_continuous(limits = c(0, 1300), breaks=seq(0, 1200, 300)) +
    # facet_wrap(~site, labeller = labeller(var = labels, site = labels2)) +
    theme1

# ggsave(here("Plots", "SOM_hf_ratiosBYWaterYield.pdf"), device = "pdf",  width = 4, height = 4, units = "in", dpi = 150)
```
<br><br>

```{r, include = FALSE}
# Nitrate
pl_hifi_no3_2 <- 
  datWithCluster2 %>% 
  left_join(hyst %>% filter(site == "Hungerford"), by = c("site", "event_start")) %>%
  ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = FI_NO3, y = HI_NO3_mean, color = as.factor(cluster)), size = 2, alpha = 0.8) +
  scale_color_manual(name = "Cluster",
                     values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
  ylim(-1, 1) + xlim(-1, 1) +
  ylab("Storm hysteresis index") + xlab("Storm flushing index") +
  theme3 +
  ggtitle("Nitrate") + 
  theme(plot.title = element_text(hjust = 0, size = 12),
        legend.position = c(0.8, 0.85),
        legend.box = "horizontal") +
  annotation_custom(text_dil, xmin=-1.45, xmax=-1.45, ymin=0, ymax=0) +
  annotation_custom(text_flu, xmin=1.2, xmax=1.2, ymin=0, ymax=0) +
  annotation_custom(text_cw, xmin=0, xmax=0, ymin=1.2, ymax=1.2) +
  annotation_custom(text_ccw, xmin=0, xmax=0, ymin=-1.4, ymax=-1.4) +
  coord_cartesian(clip = "off")

# SRP
pl_hifi_srp_2 <- 
  datWithCluster2 %>% 
  left_join(hyst %>% filter(site == "Hungerford"), by = c("site", "event_start")) %>%
  ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(aes(x = FI_SRP, y = HI_SRP_mean, color = as.factor(cluster)), size = 2, alpha = 0.8) +
  scale_color_manual(name = "Cluster",
                     values = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")) +
  ylim(-1, 1) + xlim(-1, 1) +
  ylab("Storm hysteresis index") + xlab("Storm flushing index") +
  theme3 +
  ggtitle("SRP") + 
  theme(plot.title = element_text(hjust = 0, size = 12),
        legend.position = "none") +
  annotation_custom(text_dil, xmin=-1.45, xmax=-1.45, ymin=0, ymax=0) +
  annotation_custom(text_flu, xmin=1.2, xmax=1.2, ymin=0, ymax=0) +
  annotation_custom(text_cw, xmin=0, xmax=0, ymin=1.2, ymax=1.2) +
  annotation_custom(text_ccw, xmin=0, xmax=0, ymin=-1.4, ymax=-1.4) +
  coord_cartesian(clip = "off")

# Combine the 2 plots into one
pl_HI_v_FI_alt_2 <- plot_grid(pl_hifi_no3_2, pl_hifi_srp_2, ncol = 2, align = "hv",
                            labels = "auto", hjust = -0.4, vjust = 2.5, scale = 1)
# Create common x and y axis titles
y.grob <- textGrob("Storm hysteresis index",
                   gp = gpar(fontsize = 13), rot = 90)
x.grob <- textGrob("Storm flushing index",
                   gp = gpar(fontsize = 13))
# Add axis title to plot
# test_alt <- grid.arrange(arrangeGrob(pl_HI_v_FI_alt, left = y.grob, bottom = x.grob))
# ggsave("Plots/HIFI_hf.png", test_alt, width = 6, height = 3.5, units = "in", dpi = 300)     
```
<br><br>

```{r, include = TRUE, echo = FALSE, message = FALSE, warning = FALSE}
# Add axis title to plot
# grid.arrange(arrangeGrob(pl_HI_v_FI_alt, left = y.grob, bottom = x.grob))
test_alt_2 <- grid.arrange(arrangeGrob(pl_HI_v_FI_alt_2, left = y.grob, bottom = x.grob))
# ggsave(here("Plots", "HIFI_hf.pdf"), plot = test_alt, device = "pdf", width = 6, height = 3.5, units = "in", dpi = 300)     
```